
  version:'3'
services:
  postgres:
    image: 'postgres:13'
    container_name: 'java_postgres:latest'
    enviroment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=keygen'
    volumes:
      - .:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
  app :
    build: ./
    container_name: 'java_app'
      ports:
        - "8080:8080"